:description: How user interations take effect on displayed graph and backing database


[[user-interactions]]
= How User Interations Take Effect on Displayed Graph and Backing Database

We define user interactions as ...

There are basically 3 components involved in handling users' interactions:

1. *GraphEventHandlerModel* contains implementations on how to mutate the displayed graph for various interactions
2. *Visualization* triggers the implementations via D3 callbacks
3. *VisualizationView* is involved if user interactions involve database changes

== How to Implement a User Interaction

1. Implement an event handler function in GraphEventHandlerModel
2. Bind the handler function in `GraphEventHandlerModel.bindEventHandlers()`
3. Trigger the handler function in `Visualization`
4. If the interaction involves database changes, add the corresponding logic to `GraphInteractionCallBack`, and
5. Trigger the `GraphInteractionCallBack` in the handler function

For example, let's say we want to support a easy on-graph editing by allowing us to create a new node when we double
click on canvas. 


For more infor, please see this PR: 