:description: This section describes how i18n is implemented in neo4j-arc and how to use it

[[neo4j-arc-i18n]]
= Internationalization

Default displaed text is in English if left un-translated

== How to Enable i18n in neo4j-arc

=== Intalling https://qubitpi.gitbook.io/react-i18next/[react-i18next]

[source,javascript]
----
yarn add react-i18next i18next
----

=== Load Translations

==== Add on i18next Init

We can add the translations on init by create a new file `i18n.ts` beside our `App.tsx` containing following content:

[source,typescript]
----
import i18n from 'i18next'
import { resources } from 'neo4j-arc/graph-visualization'
import { initReactI18next } from 'react-i18next'

i18n.use(initReactI18next).init({
  resources,
  lng: 'zh',
  interpolation: {
    escapeValue: false
  }
})

export default i18n
----

[NOTE]
====
* In the example above, we've configured i18n language to be Simplified Chinese
* The file does not need to be named `i18n.ts`, it can be any other filename. Just make sure it is imported accordingly.
* Those interested in the details above can refer to the
  https://qubitpi.gitbook.io/react-i18next/guides/quick-start[react-i18next documentation]
====

==== Add after Init

We can also add the translations after init:

[source,typescript]
----
import i18n from 'i18next'
import { initReactI18next } from 'react-i18next'

i18n.use(initReactI18next).init({
  resources: {},
  lng: 'zh',
  interpolation: {
    escapeValue: false
  }
})

export default i18n
----

[NOTE]
====
Note that we have passed in an empty resources object on init. This is necessary because otherwise i18next will try to
load translations and give us a warning that we are not using a backend.
====

Then we would include the following logic anywhere we would like to load translations in

[source,typescript]
----
import i18next from 'i18next';

i18next.addResources("en", "translation", resources.en.translation);
i18next.addResources("zh", "translation", resources.zh.translation);
----

=== I18nextProvider

[source,typescript]
----
import { I18nextProvider } from 'react-i18next'

import i18n from './i18n'

const App = (): JSX.Element => {
  return (
    <I18nextProvider i18n={i18n}>
      <App />
    </I18nextProvider>
  )
}
export default AppInit
----
